networks:
  gestaovagasprometheus-network:
    #driver padrão, tem outros drivers de rede
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:


services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas

  prometheus:
    container_name: prometheus_gestao_vagas
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - gestaovagasprometheus-network
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana_gestao_vagas
    image: grafana/grafana:latesta
    ports:
      - "3000:3000"
    networks:
      - gestaovagasprometheus-network